# This workflow will upload a Python Package using Poetry when a new release is created
# For more information see: https://help.github.com/en/actions/language-and-framework-guides/using-python-with-github-actions#publishing-to-package-registries

name: Publish Python Package

on:
  release:
    types: [created]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install poetry
        python -m pip install -U setuptools
    - name: Build and publish
      run: |
        poetry config pypi-token.pypi ${{ secrets.PYPI_PUBLISH_TOKEN }}
        poetry publish --build
